name: DGUT_Auto-Post

on:
  workflow_dispatch:
  schedule:
    - cron: "15 16,17,18  *  *  *"
  watch:
    types: [ started ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "requirements"
        run: pip3 install -r requirements.txt

      - name: "time"
        run:
          sudo timedatectl set-timezone Asia/Shanghai

      - name: "Run Auto-Post"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PUSHKEY: ${{ secrets.PUSHKEY }}
        run:
          python Auto-Post.py